[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.7.6"

fs_permissions = [{ access = "read-write", path = "./"}]

no_match_test = "testEchidna"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fuzz]
runs = 5000

[rpc_endpoints]
optimism_goerli = "${OPTIMISM_GOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
lisk = "${LISK_RPC_URL}"
mode = "${MODE_RPC_URL}"
bob = "${BOB_RPC_URL}"
fraxtal = "${FRAXTAL_RPC_URL}"
metal = "${METAL_RPC_URL}"

[etherscan]
optimism_goerli = { key = "${OPTIMISM_GOERLI_ETHERSCAN_API_KEY}", url = "${OPTIMISM_GOERLI_ETHERSCAN_VERIFIER_URL}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}" }
mode = { key = "${MODE_ETHERSCAN_API_KEY}", url = "${MODE_ETHERSCAN_VERIFIER_URL}" }
fraxtal = { key = "${FRAXTAL_ETHERSCAN_API_KEY}", url = "${FRAXTAL_ETHERSCAN_VERIFIER_URL}" }
metal = { key = "NA", url = "${METAL_ETHERSCAN_VERIFIER_URL}" }