name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    run-linters:
      runs-on: ubuntu-latest

      steps:
        - name: Check out github repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 1
  
        - name: Setup node.js
          uses: actions/setup-node@v1
          with:
            node-version: '18.x'
  
        - name: Set yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "::set-output name=dir::$(yarn cache dir)"
  
        - name: Restore yarn cache
          uses: actions/cache@v2
          id: yarn-cache
          with:
            path: |
              ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              ${{ runner.os }}-yarn-
        - name: Install node.js dependencies
          run: yarn --frozen-lockfile
  
        - name: Run formatter check on *.sol and *.json
          run: yarn format:check
  
        # - name: run linter check on *.sol file
        #   run: yarn lint

    run-fmt:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        # Runs a single command using the runners shell
        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
          with:
            version: v1.0.0

        - name: Format
          run: forge fmt --check